"""Новое поле mediapath

Revision ID: 0551d0c43eb3
Revises: 7f0311e9e8da
Create Date: 2024-08-23 18:35:06.421474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0551d0c43eb3'
down_revision = '7f0311e9e8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('media_path')

    # ### end Alembic commands ###
