"""Добавлен класс User_info

Revision ID: 7f0311e9e8da
Revises: dad861d317ec
Create Date: 2024-08-19 13:35:11.116604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0311e9e8da'
down_revision = 'dad861d317ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('hobby', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
